config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'admin' do
    devise_for :admins, controllers: { sessions: 'admins/sessions' }

    # admin_general_routes
    root to: 'admin#dashboard', as: 'admin/dashboard'

    #admin products routes
    resources :products, controller: 'admin/products' do
      resources :product_options, except: %i[index show], controller: 'admin/product_options'
      resources :product_variants, except: %i[index show], controller: 'admin/product_variants'
    end
    get 'load-products', to: 'admin/products#load_index', as: 'load-products'
    get 'edit-product-tax', to: 'admin/products#edit_product_tax', as: 'edit-product-tax'
    patch 'update-product-tax', to: 'admin/products#update_product_tax', as: 'update-product-tax'

    #admin taxes routes
    resources :taxes, controller: 'admin/taxes'
    get 'load-taxes', to: 'admin/taxes#load_index', as: 'load-taxes'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'website#home'
end

app/models/tax.rb
class Tax < ApplicationRecord
  include PgSearch::Model
  has_many :product_taxes, dependent: :destroy
  has_many :products, through: :product_taxes
  validates :name, presence: true, uniqueness: true
  validates :rate, presence: true
  validates :rate, numericality: { greater_than_or_equal_to: 0 }

  pg_search_scope :search_by_name,
                  against: %i[name],
                  ignoring: :accents,
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/admin/taxes_controller.rb
class Admin::TaxesController < AdminController
  before_action :authorize_admin
  before_action :set_tax, only: %i[edit update destroy]

  def index; end

  def load_index
    @taxes = Tax.all.order(:name)
    @taxes = if params[:search_index].blank?
               Tax.order(:name)
             else
               Tax.order(:name).search_by_name(params[:search_index])
             end
    render partial: 'admin/taxes/partials/load_index'
  end

  def new
    @tax = Tax.new
  end

  def create
    @tax = Tax.new(set_tax_params)
    if @tax.save
      @taxes = Tax.all.order(:name)
      flash.now.notice = "La taxe #{@tax.name} a été correctment créée"
    else
      render_turbo_flashes(:alert, "#{@tax.errors.messages.keys.first} #{@tax.errors.messages.values.first.first}")
    end
  end

  def edit; end

  def update
    if @tax.update(set_tax_params)
      @taxes = Tax.order(:name)
      flash.now.notice = "La taxe #{@tax.name} a été correctment éditée"
    else
      render_turbo_flashes(:alert, "#{@tax.errors.messages.keys.first} #{@tax.errors.messages.values.first.first}")
    end
  end

  def destroy
    if @tax.destroy
      @taxes = Tax.order(:name)
      flash.now.notice = "La taxe #{@tax.name} a été correctment suppprimée"
    else
      render_turbo_flashes(:alert, "#{@tax.errors.messages.keys.first} #{@tax.errors.messages.values.first.first}")
    end
  end

  private

  def authorize_admin
    authorize %i[admin Product]
  end

  def set_tax_params
    params.require(:tax).permit(:name, :rate)
  end

  def set_tax
    @tax = Tax.find(params[:id])
  end
end

app/views/admin/taxes/create.turbo_stream.erb
<%= turbo_stream.replace :load_taxes_index do %>
  <%= render 'admin/taxes/partials/load_index' %>
<% end %>
<%= turbo_stream.replace :tax_modal do %>
  <%= turbo_frame_tag :tax_modal, target: '_top' %>
<% end %>

app/views/admin/taxes/destroy.turbo_stream.erb
<%= turbo_stream.replace :load_taxes_index do %>
  <%= render 'admin/taxes/partials/load_index' %>
<% end %>

app/views/admin/taxes/edit.turbo_stream.erb
<%= turbo_stream.update :tax_modal do %>
  <%= render 'admin/taxes/partials/tax_form', url: tax_path, method: :patch %>
<% end %>

app/views/admin/taxes/index.html.erb
<div class="sidebar__wrapper table_wrapper" data-controller="load-index" data-load-index-url-value=<%= load_taxes_path %>>
  <div class='page-title-section'>
    <h1 class='page-title'>Taxes</h1>
  </div>
  <div class='a__box'>
    <div class='d-flex justify-content-between align-items-center'>
      <input class='col-md-5 form-control string optional' type="text" value='' placeholder='Rechercher une taxe...' id='search-index-input' data-load-index-target="searchIndex" data-action="load-index#load">
      <div class='d-flex'>
        <%= link_to new_tax_path, class: "btn btn-primary d-flex", method: :get do %>
          <%= svg 'icon_add' %>
          <span>Nouvelle taxe</span>
        <% end %>
      </div>
    </div>
  </div>
  <div data-load-index-target="inject">
    <div class="table-div-wrapper">
      <div class="table-div">
        <table class="primary-table scrollable-table sortable-table">
          <thead>
            <tr>
              <th>NOM</th>
              <th>OPTIONS</th>
            </tr>
          </thead>
          <tbody>
            <% 15.times do %>
              <tr>
                <td>
                  <div class="skeleton-text"></div>
                </td>
                <td>
                  <div class="skeleton-text"></div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<%= turbo_frame_tag :tax_modal, target: '_top' %>

app/views/admin/taxes/new.turbo_stream.erb
<%= turbo_stream.update :tax_modal do %>
  <%= render 'admin/taxes/partials/tax_form', url: taxes_path, method: :post %>
<% end %>

app/views/admin/taxes/update.turbo_stream.erb
<%= turbo_stream.replace :load_taxes_index do %>
  <%= render 'admin/taxes/partials/load_index' %>
<% end %>
<%= turbo_stream.replace :tax_modal do %>
  <%= turbo_frame_tag :tax_modal, target: '_top' %>
<% end %>