config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'admin' do
    devise_for :admins, controllers: { sessions: 'admins/sessions' }

    # admin_general_routes
    root to: 'admin#dashboard', as: 'admin/dashboard'

    #admin products routes
    resources :products, controller: 'admin/products' do
      resources :product_options, except: %i[index show], controller: 'admin/product_options'
      resources :product_variants, except: %i[index show], controller: 'admin/product_variants'
    end
    get 'load-products', to: 'admin/products#load_index', as: 'load-products'
    get 'edit-product-tax', to: 'admin/products#edit_product_tax', as: 'edit-product-tax'
    patch 'update-product-tax', to: 'admin/products#update_product_tax', as: 'update-product-tax'

    #admin taxes routes
    resources :taxes, controller: 'admin/taxes'
    get 'load-taxes', to: 'admin/taxes#load_index', as: 'load-taxes'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'website#home'
end

app/models/product_option.rb
class ProductOption < ApplicationRecord
  belongs_to :product
  has_many :variant_values, dependent: :destroy
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :product_id
end

app/controllers/admin/product_options_controller.rb
class Admin::ProductOptionsController < AdminController
  before_action :authorize_admin

  def new
    @product = Product.find(params[:product_id])
    @product_option = ProductOption.new(product_id: @product.id)
  end

  def create
    @product_option = ProductOption.new(set_product_option_params)
    if @product_option.save
      @product = @product_option.product
      flash.now.notice = "L'option #{@product_option.name} a été correctment créée"
    else
      render_turbo_flashes(:alert, "#{@product_option.errors.messages.keys.first} #{@product_option.errors.messages.values.first.first}")
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @product_option = ProductOption.find(params[:id])
  end

  def update
    @product_option = ProductOption.find(params[:id])
    if @product_option.update(set_product_option_params)
      @product = @product_option.product
      flash.now.notice = "L'option  a été correctment renommée"
    else
      render_turbo_flashes(:alert, "#{@product_option.errors.messages.keys.first} #{@product_option.errors.messages.values.first.first}")
    end
  end

  def destroy
    @product_option = ProductOption.find(params[:id])
    if @product_option.destroy
      @product = Product.find(params[:product_id])
      flash.now.notice = "L'option #{@product_option.name} a été correctment supprimée"
    else
      render_turbo_flashes(:alert, "#{@product_option.errors.messages.keys.first} #{@product_option.errors.messages.values.first.first}")
    end
  end

  private

  def authorize_admin
    authorize %i[admin ProductOption]
  end

  def set_product_option_params
    params.require(:product_option).permit(:name, :product_id)
  end
end

app/views/admin/product_options/partials/_product_option_form.html.erb
<%= simple_form_for @product_option, url: url, method: method do |f| %>
  <%= f.input :product_id,
  as: :hidden,
  wrapper_html: { class: 'mb-0' } %>
  <div class='d-flex mt-2 mb-2'>
    <%= f.input :name,
                label: false,
                required: false,
                placeholder: 'Nom',
                wrapper_html: { class: 'mr-4 mb-0' }
                %>
    <%= f.button :button, params[:action] == 'edit' ? 'Éditer' : 'Créer', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/product_options/partials/_product_options_list.html.erb
<% @product.product_options.each do |option| %>
  <%= turbo_frame_tag dom_id(option) do %>
    <li>
      <%= "#{option.name}" %>
      <%= link_to edit_product_product_option_path(id: option, product_id: @product), method: :get, class: 'very-small-icons ml-4' do %>
        <%= svg 'icon_edit' %>
      <% end %>
      <%= link_to product_product_option_path(id: option, product_id: @product), class: 'very-small-icons ml-2', method: :delete,
          data: { confirm: "Êtes-vous sûr de vouloir supprimer cet attribut ?", verify: option.name, verify_text: "Veuillez saisir '#{option.name}' pour confirmer", word_to_type: option.name } do %>
        <%= svg 'icon_trash' %>
      <% end %>
    </li>
  <% end %>
<% end %>