config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'admin' do
    devise_for :admins, controllers: { sessions: 'admins/sessions' }

    # admin_general_routes
    root to: 'admin#dashboard', as: 'admin/dashboard'

    #admin products routes
    resources :products, controller: 'admin/products' do
      resources :product_options, except: %i[index show], controller: 'admin/product_options'
      resources :product_variants, except: %i[index show], controller: 'admin/product_variants'
    end
    get 'load-products', to: 'admin/products#load_index', as: 'load-products'
    get 'edit-product-tax', to: 'admin/products#edit_product_tax', as: 'edit-product-tax'
    patch 'update-product-tax', to: 'admin/products#update_product_tax', as: 'update-product-tax'

    #admin taxes routes
    resources :taxes, controller: 'admin/taxes'
    get 'load-taxes', to: 'admin/taxes#load_index', as: 'load-taxes'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'website#home'
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  has_many :product_options, dependent: :destroy
  has_many :product_taxes, dependent: :destroy
  has_many :taxes, through: :product_taxes
  has_many :product_variants

  accepts_nested_attributes_for :product_options, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :product_taxes, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: true

  pg_search_scope :search_by_name,
                  against: %i[name],
                  ignoring: :accents,
                  using: {
                    tsearch: { prefix: true }
                  }

  def main_variant
    product_variants.find_by(is_main: true)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :authorize_admin
  before_action :define_product, only: %i[show edit update]

  def index; end

  def load_index
    @products = if params[:search_index].blank?
                  Product.order(:name).includes(:product_variants)
                else
                  Product.order(:name).search_by_name(params[:search_index]).includes(:product_variants)
                end
    render partial: 'admin/products/partials/load_index'
  end

  def show; end

  def new
    @product = Product.new
    @product.product_options.build
  end

  def create
    @product = Product.new(set_product_params)
    if @product.save
      redirect_to product_path(@product), notice: 'Le produit à été correctement créé'
    else
      render_turbo_flashes(:alert, "#{@product.errors.messages.keys.first} #{@product.errors.messages.values.first.first}")
    end
  end

  def edit; end

  def update
    if @product.update(set_product_params)
      flash.now.notice = "Le produit à été correctement édité"
    else
      render_turbo_flashes(:alert, "#{@product.errors.messages.keys.first} #{@product.errors.messages.values.first.first}")
    end
  end

  def edit_product_tax
    @product_tax = ProductTax.find(params[:id])
  end

  def update_product_tax
    @product_tax = ProductTax.find(params[:id])
    if @product_tax.update(set_product_tax_params)
      flash.now.notice = "La taxe pour ce produit a été correctement mise à jour"
    else
      render_turbo_flashes(:alert, "#{@product_tax.errors.messages.keys.first} #{@product_tax.errors.messages.values.first.first}")
    end
  end

  private

  def authorize_admin
    authorize %i[admin Product]
  end

  def define_product
    @product = Product.find(params[:id])
  end

  def set_product_params
    params.require(:product).permit(:name, :tax_ids, product_options_attributes: %i[name product_id _destroy])
  end

  def set_product_tax_params
    params.require(:product_tax).permit(:product_id, :tax_id)
  end
end

app/views/admin/products/edit.turbo_stream.erb
<%= turbo_stream.update :edit_product do %>
  <%= render 'admin/products/partials/edit_product_form', url: product_path(id: @product), method: :patch %>
<% end %>

app/views/admin/products/edit_product_tax.turbo_stream.erb
<%= turbo_stream.update dom_id(@product_tax) do %>
  <%= render 'admin/products/partials/product_tax_form', url: update_product_tax_path(id: @product_tax.id), method: :patch %>
<% end %>

app/views/admin/products/index.html.erb
<div class="sidebar__wrapper table_wrapper" data-controller="load-index" data-load-index-url-value=<%= load_products_path %>>
  <div class='page-title-section'>
    <h1 class='page-title'>Produits</h1>
  </div>
  <div class='a__box'>
    <div class='d-flex justify-content-between align-items-center'>
      <input class='col-md-5 form-control string optional' type="text" value='' placeholder='Rechercher un produit...' id='search-index-input' data-load-index-target="searchIndex" data-action="load-index#load">
      <div class='d-flex'>
        <%= link_to new_product_path, class: "btn btn-primary d-flex" do %>
          <%= svg 'icon_add' %>
          <span>Nouveau produit</span>
        <% end %>
      </div>
    </div>
  </div>
  <div data-load-index-target="inject">
    <div class="table-div-wrapper">
      <div class="table-div">
        <table class="primary-table scrollable-table sortable-table">
          <thead>
            <tr>
              <th>NOM</th>
              <th class="col-email">EMAIL</th>
              <th>NIVEAU DE PERMISSION</th>
              <th class="col-options">OPTIONS</th>
            </tr>
          </thead>
          <tbody>
            <% 15.times do %>
              <tr>
                <td>
                  <div class="skeleton-text"></div>
                </td>
                <td class="col-email">
                  <div class="skeleton-text"></div>
                </td>
                <td>
                  <div class="skeleton-text"></div>
                </td>
                <td class="col-options">
                  <div class="skeleton-text"></div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="sidebar__wrapper">
  <div class='page-title-section'>
    <h1 class='page-title'>Nouveau Produit</h1>
  </div>
  <%= turbo_frame_tag :create_product, target: '_top' do %>
    <%= render 'admin/products/partials/new_product_form', url: products_path, method: :post %>
  <% end %>
</div>

app/views/admin/products/show.html.erb
<div class="sidebar__wrapper">
  <div class='page-title-section'>
    <h1 class='page-title'>
      <%= turbo_frame_tag :product_title do %><%= @product.name %><% end %>
    </h1>
  </div>
  <div class='a__box mb-3'>
    <p class='section-title mb-3'>Nom</p>
    <%= turbo_frame_tag :edit_product do %>
      <%= render 'admin/products/partials/edit_product_section' %>
    <% end %>
  </div>
  <div class='a__box mb-3'>
    <p class='section-title mb-3'>Taxes</p>
    <% @product.product_taxes.includes(:tax).each do |pt| %>
      <%= turbo_frame_tag dom_id(pt) do %>
        <%= "#{pt.tax.name} : #{pt.tax.rate} %" %>
        <%= link_to edit_product_tax_path(id: pt), method: :get, class: 'very-small-icons ml-4' do %>
          <%= svg 'icon_edit' %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class='a__box mb-3'>
    <p class='section-title mb-3'>Attributs</p>
    <%= turbo_frame_tag :product_options_list do %>
      <%= render 'admin/product_options/partials/product_options_list' %>
    <% end %>
    <%= turbo_frame_tag :new_product_option %>
    <%= link_to 'Ajouter un attribut', new_product_product_option_path(@product), class: 'btn mt-3', method: :get %>
  </div>
  <div class='a__box'>
    <p class='section-title mb-3'>Variants</p>
    <%= turbo_frame_tag :product_variants, target: :_top do %>
      <%= render 'admin/product_variants/partials/load_index' %>
    <% end %>
    <%= link_to 'Ajouter un Variant', new_product_product_variant_path(@product), class: 'btn mt-3', method: :get %>
  </div>
</div>
<%= turbo_frame_tag :product_modal, target: '_top' %>

app/views/admin/products/update.turbo_stream.erb
<%= turbo_stream.update :edit_product do %>
  <%= render 'admin/products/partials/edit_product_section' %>
<% end %>
<%= turbo_stream.update :product_title do %>
  <%= @product.name %>
<% end %>

app/views/admin/products/update_product_tax.turbo_stream.erb
<%= turbo_stream.update dom_id(@product_tax) do %>
  <%= "#{@product_tax.tax.name} : #{@product_tax.tax.rate} %" %>
  <%= link_to edit_product_tax_path(id: @product_tax), method: :get, class: 'very-small-icons ml-4' do %>
    <%= svg 'icon_edit' %>
  <% end %>
<% end %>