config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'admin' do
    devise_for :admins, controllers: { sessions: 'admins/sessions' }

    # admin_general_routes
    root to: 'admin#dashboard', as: 'admin/dashboard'

    #admin products routes
    resources :products, controller: 'admin/products' do
      resources :product_options, except: %i[index show], controller: 'admin/product_options'
      resources :product_variants, except: %i[index show], controller: 'admin/product_variants'
    end
    get 'load-products', to: 'admin/products#load_index', as: 'load-products'
    get 'edit-product-tax', to: 'admin/products#edit_product_tax', as: 'edit-product-tax'
    patch 'update-product-tax', to: 'admin/products#update_product_tax', as: 'update-product-tax'

    #admin taxes routes
    resources :taxes, controller: 'admin/taxes'
    get 'load-taxes', to: 'admin/taxes#load_index', as: 'load-taxes'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'website#home'
end

app/views/layouts/partials/_admin_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light admin-navbar">
  Bonjour <%= current_admin.first_name %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown u-cursor-pointer">
        <%= image_tag "https://res.cloudinary.com/francois-adrien/image/upload/v1639655188/default-avatar_copie_b5zbm2.png", class: "avatar-square dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/partials/_admin_sidebar.html.erb
<div class="sidebar" data-controller='sidebar'>
  <div class='admin-sidebar-logo'>
    <%= image_tag "https://res.cloudinary.com/francois-adrien/image/upload/v1639668869/Logo_CA_Couleurs_CMJN_copie_2_fj8x50.jpg" %>
  </div>
  <nav class='admin-nav w-100'>
    <div class="sidebar__links">
      <%= link_to root_path do %>
        <div class="sidebar__link main_link align-items-center <%= 'active-tab' if dashboard_tab_active %>">
          <%= svg 'icon_dashboard' %>
          <p class="ml-2">Dashboard</p>
        </div>
      <% end %>
      <div class="sidebar__link main_link align-items-center <%= 'active-tab tab-deployed' if store_tab_active %>" id='sidebar-store-link' data-action='click->sidebar#deploySection' data-value='j-sidebar-store-div'>
        <%= svg 'icon_store' %>
        <p class="ml-3">Boutique</p>
      </div>
      <div class='<%= 'u-display-none' unless store_tab_active %>' id='j-sidebar-store-div'>
        <%= link_to products_path, class: '' do %>
          <div class="sidebar__link sublink align-items-center <%= 'active-tab' if products_tab_active %>">
            <%= svg 'icon_box_open' %>
            <p class="ml-2">Produits</p>
          </div>
        <% end %>
        <%= link_to taxes_path, class: '' do %>
          <div class="sidebar__link sublink align-items-center <%= 'active-tab' if taxes_tab_active %>">
            <%= svg 'icon_percentage' %>
            <p class="ml-2">Taxes</p>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</div>